import nodemailer from "nodemailer";

export const DAILY_REPORT_RECIPIENTS = ["ansar@godigitell.com", "preetha@godigitell.com"];

const SMTP_HOST = process.env.SMTP_HOST;
const SMTP_PORT = parseInt(process.env.SMTP_PORT || "587", 10);
const SMTP_USER = process.env.SMTP_USER;
const SMTP_PASS = process.env.SMTP_PASS;
const SMTP_FROM = process.env.SMTP_FROM || SMTP_USER || "no-reply@godigitell.com";

export function isEmailConfigured(): boolean {
  return Boolean(SMTP_HOST && SMTP_USER);
}

function createTransport() {
  return nodemailer.createTransport({
    host: SMTP_HOST,
    port: SMTP_PORT,
    secure: SMTP_PORT === 465,
    auth: {
      user: SMTP_USER,
      pass: SMTP_PASS,
    },
  });
}

export interface DailyReportTask {
  title: string;
  client: string;
  status: string;
  type: "CALENDAR" | "ADHOC";
}

export interface DailyReportEmailData {
  date: string;
  employeeName: string;
  employeeEmail: string;
  loginTime: string | null;
  logoutTime: string | null;
  hoursWorked: number | null;
  tasks: DailyReportTask[];
}

function buildDailyReportHtml(data: DailyReportEmailData): string {
  const taskRows = data.tasks
    .map(
      (t) => `
      <tr>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;">${t.title}</td>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;">${t.client}</td>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;">${t.type === "CALENDAR" ? "Calendar" : "Adhoc"}</td>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;">${t.status.replace(/_/g, " ")}</td>
      </tr>`
    )
    .join("");

  const tasksBlock =
    data.tasks.length > 0
      ? `<table style="border-collapse:collapse;width:100%;font-size:13px;">
            <thead>
              <tr style="background:#f3f4f6;">
                <th style="padding:8px 12px;border:1px solid #e5e7eb;text-align:left;">Task</th>
                <th style="padding:8px 12px;border:1px solid #e5e7eb;text-align:left;">Client</th>
                <th style="padding:8px 12px;border:1px solid #e5e7eb;text-align:left;">Type</th>
                <th style="padding:8px 12px;border:1px solid #e5e7eb;text-align:left;">Status</th>
              </tr>
            </thead>
            <tbody>${taskRows}</tbody>
          </table>`
      : `<p style="color:#6b7280;font-size:13px;">No tasks were tracked for this day.</p>`;

  return `
  <div style="font-family:Arial,Helvetica,sans-serif;max-width:640px;margin:0 auto;">
    <h2 style="color:#4f46e5;margin-bottom:4px;">Daily Work Report</h2>
    <p style="color:#374151;font-size:14px;margin:4px 0;">${data.employeeName} &middot; ${data.date}</p>
    <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:12px 16px;margin:12px 0;font-size:13px;color:#374151;">
      <p style="margin:4px 0;"><strong>Check-in:</strong> ${data.loginTime || "-"}</p>
      <p style="margin:4px 0;"><strong>Check-out:</strong> ${data.logoutTime || "-"}</p>
      <p style="margin:4px 0;"><strong>Hours worked:</strong> ${data.hoursWorked != null ? `${data.hoursWorked}h` : "-"}</p>
      <p style="margin:4px 0;"><strong>Total tasks:</strong> ${data.tasks.length}</p>
    </div>
    <h3 style="color:#111827;font-size:15px;margin:12px 0 8px;">Tasks</h3>
    ${tasksBlock}
    <p style="color:#9ca3af;font-size:11px;margin-top:16px;">Generated by godigitell Work Organiser</p>
  </div>`;
}

export async function sendDailyReportEmail(data: DailyReportEmailData): Promise<boolean> {
  if (!isEmailConfigured()) {
    console.warn("[email] SMTP not configured; skipping daily report email.");
    return false;
  }
  try {
    const transport = createTransport();
    await transport.sendMail({
      from: SMTP_FROM,
      to: DAILY_REPORT_RECIPIENTS,
      subject: `Daily Work Report - ${data.employeeName} - ${data.date}`,
      html: buildDailyReportHtml(data),
    });
    return true;
  } catch (error) {
    console.error("[email] Failed to send daily report email:", error);
    return false;
  }
}